# This file was generated by GoReleaser. DO NOT EDIT.
cask "sdkkeeper" do
  name "SDK Keeper"

  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "9ef20ffebb0959372936163a71809ccd97e804e4748d100003ee4e28a92f28d6"
      url "https://github.com/kumar-github/sdkkeeper/releases/download/v#{version}/sdkkeeper_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "902265919350aac09fc505451d89b43385180631892fb467498cf46891c87bec"
      url "https://github.com/kumar-github/sdkkeeper/releases/download/v#{version}/sdkkeeper_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ff31d2ac3b32b4957f0f9105b787f311cc58ea1dbcb81e1ad73a494768a83b6d"
      url "https://github.com/kumar-github/sdkkeeper/releases/download/v#{version}/sdkkeeper_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8357383cafd5d90aeb2289c9f1533502aca009770abc9bf0e7de0574008868dd"
      url "https://github.com/kumar-github/sdkkeeper/releases/download/v#{version}/sdkkeeper_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sdkkeeper"
  desc "SDK Keeper -- explicit, no-default SDK version manager"
  homepage "https://github.com/kumar-github/sdkkeeper"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sk"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sk"]
    end
  end

  uninstall_postflight do
    system_command "/bin/echo", args: ["SDK Keeper has been removed."]
    system_command "/bin/echo", args: ["If you added the shell integration line to ~/.zshrc, you may want to remove it too:"]
    system_command "/bin/echo", args: ["  sed -i '' '/eval.*sk init zsh/d' ~/.zshrc"]
  end

  # No zap stanza required

  caveats <<~EOS
    SDK Keeper is installed. The command is `sk` (not sdkkeeper) -- and it needs one more step to actually work in your shell:

      echo 'command -v sk >/dev/null && eval "$(sk init zsh)"' >> ~/.zshrc

    Then restart your shell (or run: source ~/.zshrc)

    If you ever uninstall SDK Keeper, remove that line from ~/.zshrc too:
      sed -i '' '/eval.*sk init zsh/d' ~/.zshrc
  EOS
end
