# This file was generated by GoReleaser. DO NOT EDIT.
cask "sdkkeeper" do
  name "SDK Keeper"

  caveats do
    zshrc_path = `zsh -c 'print -r -- "${ZDOTDIR:-$HOME}/.zshrc"' 2>/dev/null`.strip
    zshrc_path = File.join(ENV["HOME"], ".zshrc") if zshrc_path.empty?
    <<~EOS
      SDK Keeper is installed. The command is `sk` (not sdkkeeper).

      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Setup ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

      Add the below block at the end of your shell config file (#{zshrc_path}).

        # SDK Keeper
        eval "$(sk init zsh)"

      Then restart your shell (or re-source that same file).

      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Usage ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

      Just type `sk` and hit enter. You will know what to do next.

      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Cleanup ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

      1. Remove the below block from your shell config file (#{zshrc_path}) after uninstalling SDK Keeper.

        # SDK Keeper
        eval "$(sk init zsh)"

      2. Delete the hidden `.sdkkeeper` folder from the user home directory (typically ~/.sdkkeeper).
      Note: This is where all the downloaded JDKs and SDKs are stored and deleting them is permanant. You can keep them if you want to use them later.
    EOS
  end

  version "0.1.11"

  on_macos do
    on_arm do
      sha256 "80a0a83eb4cc3fefe034f630f32708ad369bee6018620ebf0108e0058c0d49a5"
      url "https://github.com/kumar-github/sdkkeeper/releases/download/v#{version}/sdkkeeper_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1df49336c646d04d2bcb82bafcf09ac2eb2c844eb533654339ff86edd627f9f7"
      url "https://github.com/kumar-github/sdkkeeper/releases/download/v#{version}/sdkkeeper_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "de47b5b07778b16828228f3476bf6a33a239143ad747a01b34543dac61a1c900"
      url "https://github.com/kumar-github/sdkkeeper/releases/download/v#{version}/sdkkeeper_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "abedad9d02c3a82c15b974deb2e9abca830fdf5b5a06b1094a2fbe2aa40d1cf8"
      url "https://github.com/kumar-github/sdkkeeper/releases/download/v#{version}/sdkkeeper_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sdkkeeper"
  desc "SDK Keeper -- explicit, no-default SDK version manager"
  homepage "https://github.com/kumar-github/sdkkeeper"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sk"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sk"]
    end
  end

  # No zap stanza required
end
